steps:
#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/project-kubernetes-242705/welcome:latest || exit 0'
  ]
#step 2
- name: 'gcr.io/cloud-builders/docker'
  args: [
   'build',
   '-t',
   'gcr.io/project-kubernetes-242705/welcome:$BRANCH_NAME-$COMMIT_SHA',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=poc-cluster'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'welcome-app',
   'welcome-app=gcr.io/project-kubernetes-242705/welcome:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=poc-cluster'
# push images to Google Container Registry with tags
images: [
   'gcr.io/project-kubernetes-242705/welcome:$BRANCH_NAME-$COMMIT_SHA',
  ]
