---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "welcome-app"
  namespace: "default"
  labels:
    app: "welcome-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "welcome-app"
  template:
    metadata:
      labels:
        app: "welcome-app"
    spec:
      containers:
      - name: "welcome-sha256"
        image: "gcr.io/project-kubernetes-242705/welcome@sha256:9329920a23a15b8600b7ddf9d5e2b14f89b5ea251c94f55f184751ee41cd813c"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "welcome-app-hpa"
  namespace: "default"
  labels:
    app: "welcome-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "welcome-app"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
