---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "welcome-app-service"
  namespace: "default"
  labels:
    app: "welcome-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "welcome-app"
  type: "LoadBalancer"
  loadBalancerIP: ""
